# Generated by Django 5.1.1 on 2026-02-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcat_name',
        ),
    ]
